CREATE DATABASE authboss;

use authboss;

CREATE TABLE user (
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (email)
)
  ENGINE =InnoDB
  DEFAULT CHARSET =utf8;
